load("//aelps/infra/compat:python.bzl", "py_package", "py_test")

py_package(
    name = "apartment_sarch",
    srcs = [
        "analyse_search.py",
        "apply_comparis.py",
        "search.py",
    ],
    data = [

    ],
    test_deps = [

    ],
    test_ini = "tests/pytest.ini",
    test_srcs = [

    ],
    deps = [
        "@pypi//:pytest",
        "@pypi//:pysbb",
        "@pypi//:pyselenium",
        "@pypi//:pypandas",
        "@pypi//:requests",
        "@pypi//:pybeautifulsoup4",
    ],
)